/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bookreader.ui;

import com.bookreader.model.User;
import com.bookreader.model.UserInteractionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ardau
 */
public class Signup extends javax.swing.JDialog {

    private final UserInteractionListener listener;

    /**
     * Creates new form Signup
     *
     * @param parent
     * @param modal
     * @param listener
     */
    public Signup(java.awt.Frame parent, boolean modal, UserInteractionListener listener) {
        super(parent, modal);
        this.listener = listener;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Signup");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        location = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lastName = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        name = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        username = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        password = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        cpassword = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        age = new javax.swing.JTextArea();
        signup = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        jLabel5.setText("Confirm Password:");

        jLabel7.setText("Location:");

        jLabel8.setText("Age:");

        location.setColumns(10);
        location.setRows(5);
        jScrollPane1.setViewportView(location);

        lastName.setColumns(10);
        lastName.setRows(5);
        jScrollPane2.setViewportView(lastName);

        name.setColumns(10);
        name.setRows(5);
        jScrollPane3.setViewportView(name);

        username.setColumns(10);
        username.setRows(5);
        jScrollPane4.setViewportView(username);

        password.setColumns(10);
        password.setRows(5);
        jScrollPane5.setViewportView(password);

        cpassword.setColumns(10);
        cpassword.setRows(5);
        jScrollPane6.setViewportView(cpassword);

        age.setColumns(10);
        age.setRows(5);
        jScrollPane8.setViewportView(age);

        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signup))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup)
                    .addComponent(clear))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        resetAllFields();
    }//GEN-LAST:event_clearActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        if (signupIsValid()) {

            try {

                ArrayList userId = new ArrayList();
                ArrayList rowList = new ArrayList();
                try {
                    Class.forName("com.mysql.jdbc.Connection");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                }

                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/books", "root", "");

                Statement stmt = (Statement) con.createStatement();
                Statement stmt1 = (Statement) con.createStatement();

                ResultSet rs = stmt.executeQuery("SELECT * FROM `bx_users` order by user_id DESC limit 1 ");

                ResultSet rs1 = stmt1.executeQuery("SELECT COUNT(*) AS total FROM new_user");

                while (rs.next()) {

                    int ID = rs.getInt("user_id");

                    userId.add(ID);

                }
                while (rs1.next()) {

                    int rowSize = rs1.getInt("total");

                    rowList.add(rowSize);

                }

                User user = new User();
                user.setName(this.name.getText());
                user.setLastName(this.lastName.getText());
                user.setUsername(this.username.getText());
                user.setLocation(this.location.getText());
                user.setAge(this.age.getText());
                user.setCpassword(this.cpassword.getText());
                user.setPassword(this.password.getText());

                int lastId = (int) userId.get(userId.size() - 1) + (int) rowList.get(rowList.size() - 1);

                if ((int) rowList.get(rowList.size() - 1) == 0) {

                    lastId++;
                    user.setUserid("" + lastId);

                } else if ((int) rowList.get(rowList.size() - 1) != 0) {

                    lastId = (int) userId.get(userId.size() - 1) + (int) rowList.get(rowList.size() - 1);

                    user.setUserid("" + lastId);

                }

                if (this.listener.signup(user)) {

                    dispose();

                } else {

                    JOptionPane.showMessageDialog(null, "Sorry,cannot signup user with the specified values", "Please chech your form again", JOptionPane.WARNING_MESSAGE);

                }

            } catch (SQLException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            JOptionPane.showMessageDialog(null, "Username must not be empty", "Please check your form again", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea age;
    private javax.swing.JButton clear;
    private javax.swing.JTextArea cpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea lastName;
    private javax.swing.JTextArea location;
    private javax.swing.JTextArea name;
    private javax.swing.JTextArea password;
    private javax.swing.JButton signup;
    private javax.swing.JTextArea username;
    // End of variables declaration//GEN-END:variables

    private void resetAllFields() {
        this.name.setText(null);
        this.lastName.setText(null);
        this.location.setText(null);
        this.password.setText(null);

        this.username.setText(null);
        this.age.setText(null);
        this.cpassword.setText(null);

    }

    private boolean signupIsValid() {
        return !this.username.getText().isEmpty();
    }
}
